### ISSUE TITLE
Таски 25.01

### ISSUE THREAD

**Issue by DmitryTsyganov** [RmRfBereza/Server#8]
- убрать робота при ожидании старта
- при рестарте присваивать камере поворот вокруг оси y игрока
- переделать финиш, чтобы он вмешался в сегмент
- поменять текст look up to start при рестарте 
- добавить разных видов препятствий
- описать таск про уровни

**Comment by DmitryTsyganov** [comment]
- опустить такси, чтобы оно касалось земли

**Comment by DmitryTsyganov** [comment]
- добавить препятствия на все сегменты

**Comment by DmitryTsyganov** [comment]
- обернуть камеру в BoxCollider, который не сталкивается с препятствиями
- убрать кнопки 2d и 3d под кнопку "Мультиплеер"

**Comment by AlexandraSmirnova** [comment]
Насчет 'убрать кнопки 2d и 3d под кнопку "Мультиплеер" ' это бы здорово улучшило интерфейс. Также предлагаю убрать форму и показывать ее только после нажатия на 3d клиент, так как не очевидно почему при нажатии этой кнопки ничего не происходит. А так будет ясно - надо ввести код

**Comment by LordNeznay** [comment]
Хочу сцену, на которую можно выкидывать пользователя с управляемой надписью (типа "соединение не удалось", "второй игрок отключился" и т.п.)

**Comment by DmitryTsyganov** [comment]
Здесь всё, кроме оборачивания камеры в коллайдер. Создам отдельный таск
